### ISSUE TITLE
Fundamental-mode snippets pi and phi conflict with julia-latexsub

### ISSUE THREAD

**Issue by ashiklom** [hlissner/doom-snippets#39]
The snippets `pi` and `phi` are defined for `fundamental-mode` to expand to their respective values (preceded by a `#-*- mode: snippet -*-` line, but that's a separate problem...).

However, in `julia-mode`, it's common practice to use LaTeX substitution to insert unicode characters (e.g. `\theta` followed by `TAB` runs `julia-latexsub-or-indent` to produce `θ`).

I'm not sure how common it is to insert the values of `phi` and `pi` in a buffer, but perhaps these could be revised somehow to avoid this conflict? I'm not a snippet master, but maybe there's a way to have them only work if they are whole words? Personally, I'd be inclined to redefine them to `pival` and `phival` or similar. Alternatively, is there a way to disable specific snippets without modifying the source of this package?

**Comment by yoavm448** [comment]
They also sometimes accidentaly complete with normal latex buffers and expand for me when I'm  meaning to pass field in nested snippets. 

I think we can disable them by creating a new overriding snippet with the same `uuid`, and give it a `nil` condition so it would never expand. I'll look into that.

**Comment by rjpower4** [comment]
Has this been fixed yet. I pulled in the most recent version and I'm still getting the snippet when trying `\phi`

**Comment by benneti** [comment]
It should be fixed. Could you check Wetter you still have old "compiled" files. Ie. Could you check wether rebuilding the package files helps?

**Comment by rjpower4** [comment]
Unfortunately, after running `doom build`, `doom compile juila-mode`, and several other variations of that still give me the snippit for `\phi`, what's the command you have in mind when you say "rebuilding the package files"?

**Comment by benneti** [comment]
Did you unpin the package? If you did, you could apropos a function defined in doom-snippets follow to the file and check whether phi is still in the fundamental mode snippets folder, if yes there are still old files. If not the problem needs to be investigated further.

**Comment by rjpower4** [comment]
Yes, with `julia-mode` unpinned, phi is still in the fundamental-mode snippets folder.

**Comment by benneti** [comment]
ah you have to unpin doom-snippets

**Comment by hlissner** [comment]
Ah, my bad. I hadn't bumped doom-snippets in doom yet. Just did it in https://github.com/hlissner/doom-emacs/commit/1dfe690f36958adc6d382c0c3465c17586ae9a85, so I'll consider this resolved. Thanks for reminding me!

**Comment by benneti** [comment]
Thank you!

**Comment by rjpower4** [comment]
Awesome, it is working now. Thank you both!
