### ISSUE TITLE
Update org-mode snippets to use lowercase for blocks

### ISSUE THREAD

**Issue by bdarcus** [hlissner/doom-snippets#46]
It seems that org is transitioning to use lowercase on blocks, and that early last year, yasnippet adopted this in their org-mode templates.

Could you update so that Doom is providing these? Right now, there are a confusing mix.

https://github.com/AndreaCrotti/yasnippet-snippets/issues/303

**Comment by hlissner** [comment]
Sorry for the tremendously late response. As of #51 this should be fixed. Thanks for bringing it to my attention!
