### ISSUE TITLE
doom sync is giving me "Symbol's function definition is void" when doing a fresh install

### ISSUE THREAD

**Issue by mslot** [hlissner/doom-snippets#67]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for solutions.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

When doing `doom sync` i expected it to do a full sync.

### What actually happened?

What i saw after doing a `doom sync` was a this error when compiling doom-snippets

> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    ✓ Successfully generated "~/.emacs.d/.local/env"
  > Installing packages...
    - Checked out doom-snippets: afe549bd63403cec5187371ec1986e68a9e5ee3c
    → Building doom-snippets...
    x There was an unexpected error
      Message: Symbol's function definition is void
      Data: (void-function . emacs-lisp-mode-mode)
      Backtrace:
        (emacs-lisp-mode-mode)
        (hack-one-local-variable mode emacs-lisp-mode)
        (hack-local-variables-apply)
        (hack-local-variables no-mode)
        (normal-mode t)
        (byte-compile-file "/home/mslot/.emacs.d/.local/straight/build-28.0.50/doo
        (byte-recompile-file "/home/mslot/.emacs.d/.local/straight/build-28.0.50/d
        (#[0 "\304\242\205\332\300\304\242@\240\210\312\313\300\242\"\210\314\30
        (byte-recompile-directory "/home/mslot/.emacs.d/.local/straight/build-28.0
        (progn (fset #'write-region vnew) (ignore write-region) (byte-recompile-di

### Describe your attempts to resolve the issue

I have tried to do a full reinstall:
1. rm -rf ~/git/emacs
2. git clone git://git.savannah.gnu.org/emacs.git ~/git/emacs
3. `./autogen`
4. `./configure --with-native-compilation -with-json --with-modules --with-harfbuzz --with-compress-install \
   --with-threads --with-included-regex --with-x-toolkit=lucid --with-zlib --with-jpeg --with-png --with-imagemagick --with-tiff --with-xpm --with-gnutls \
   --with-xft --with-xml2 --with-mailutils`
5. `make`
6. `sudo make install`
7. `git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d`
8. `doom install` - the bin is already in my path

This gives me the same error.

I have also tried to do a `doom build` followed by a `doom sync`. Still the same.

### Steps to reproduce

1. rm -rf ~/git/emacs
2. git clone git://git.savannah.gnu.org/emacs.git ~/git/emacs
3. `./autogen`
4. `./configure --with-native-compilation -with-json --with-modules --with-harfbuzz --with-compress-install \
   --with-threads --with-included-regex --with-x-toolkit=lucid --with-zlib --with-jpeg --with-png --with-imagemagick --with-tiff --with-xpm --with-gnutls \
   --with-xft --with-xml2 --with-mailutils`
5. `make`
6. `sudo make install`
7. `git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d`
8. `doom install` - the bin is already in my path
9. Optionally: `doom build`

### System Information

https://pastebin.com/t1CPXhHT

**Comment by hlissner** [comment]
Bizarre issue. I suspect there is a deeper, underlying cause, but after f7747da (for doom-snippets) and 8492e9b (for Doom) you shouldn't see this symptom at least. Let me know if that isn't the case and I'll reopen it.

**Comment by ericsolomon** [comment]
I was seeing the same issue and just completed a fresh install / sync on the latest with no issues

**Comment by hlissner** [comment]
> I was seeing the same issue and just completed a fresh install / sync on the latest with no issues

Include the backtrace please.

**Comment by ericsolomon** [comment]
Apologies, I was more trying to express that the latest commit resolved the issue for me rather than that I was just having the same issue.

For future reference, I checked out the commit in question and grabbed the error log

https://gist.github.com/ericsolomon/501fe75ef6dde0c22d0948d382abcb5f
